keras-team/keras-preprocessing

keras_preprocessing/image.py
According to the docs, `rotation_range: Int. Degree range for random rotations.`
but the default parameter and its example usages were passing float
=> Fix the default value of rotation_range

keras_preprocessing/text.py, tests/text_test.py
Fixed the oov_token to take the index as 1 by default. This includes the oov_token everytime when num_words is specified in the argument. Also written tests for this problem. 
Before, even when num_words and oov_token was specified, the sequences returned did not contain the oov_token. This fixes that.
Also added support for reverse mapping. In other words, if we do tokenizer.sequenes_to_texts(sequences), we get a list of strings. It converts indices to strings using a index_word mapping.
For sequences to texts conversion, I am replacing the words not in the vocabulary(includes 0 which might be used for padding) by the oov_token (if specified). Is that decision fine? WDYT? @fchollet
=> Fixed oov_token with num_words and added support for reverse mapping(indices to text)

keras_preprocessing/image.py
This PR proposes a minor spelling fix (`ransformed` --> `transformed`) in the docstring of `ImageDataGenerator.apply_transform`.
=> docs: minor spelling fix in `.apply_transform`

keras_preprocessing/sequence.py, keras_preprocessing/text.py, tests/sequence_test.py, tests/text_test.py
Serde for text and sequence preprocessing (will do image in a follow-up PR). Serializes objects to JSON in usual Keras-style, comes with unit tests.
Note to reviewer: Where possible we store data as plain text. This is done so that other projects (not necessarily Python) can pick up the configs and restore them. Particularly, I'll write preprocessor loaders for DL4J in Java.
Autogen docs should pick up these additions, but I'm not 100% how this works with this separate project.
---
=> Serialize text and sequence preprocessing

keras_preprocessing/text.py
Currently the documentation on https://keras.io/preprocessing/text/ is breaking when trying to display the `` ` `` character in the default filter. 
Wrapping in additional backticks fixes this in markdown.
=> Update markdown in text.py for documentation

keras_preprocessing/sequence.py, tests/sequence_test.py
Add support for `value` parameter as a string to `pad_sequences`.
=> pad_sequences: Add support for string value.

keras_preprocessing/image.py
In a previous PR we removed the parent type of Iterator which is important when using the Iterator object with Keras. (*_generator especially).
This sets the Iterator type if possible.
Fixes https://github.com/keras-team/keras-preprocessing/issues/51
=> Use Sequence if available

keras_preprocessing/image.py, tests/image_test.py
Summary
A small improvement that fixes a problem that could take days to debug.
In case the initial numpy arrays used for ImageDataGenerator.flow() are sorted by class, which can be the case if the user's code is reading images class by class, there is a high chance that the class frequencies in the resulting training and tests will differ. In the worst case, the training set will contain only samples of one class and the test set samples of another class, which would lead to poor model generalization.
The proposed patch fixes the problem by shuffling numpy arrays before they are split into training and validation.
Related Issues
The issue happened to me at work. I've fixed it rather than opening an issue.
PR Overview
•[n] This PR requires new unit tests [y/n] (make sure tests are …
=> Ensure that ImageDataGenerator.flow() generates stratified training and test sets even if the passed numpy arrays are sorted by class

keras_preprocessing/image.py, tests/image_test.py
=> Fix small typeerror bug in flow_from_dataframe when y_col is str and class_mode is "other"

keras_preprocessing/text.py, tests/text_test.py
`Tokenizer.texts_to_sequences` was only using `Tokenizer.num_words - 1` words. Now it uses `Tokenizer.num_words` words.
#52
=> Fix Tokenizer.texts_to_sequences to use a maximum of Tokenizer.num_words words

keras_preprocessing/image.py
This PR removes the function _count_valid_files_in_directory which is used to count the files in the directory, the same operation is again performed by the function _list_valid_filenames_in_directory, So I have removed the function _count_valid_files_in_directory and use _list_valid_filenames_in_directory to find the count by finding the length of the listed files.
Performance
=> remove _count_valid_files_in_directory for performance boost

keras_preprocessing/text.py
Unescaped tabs and newlines in docstring cause the document being rendered improperly.
=> Escape tabs and newlines in docstring

keras_preprocessing/image.py, tests/image_test.py
Fix ext_exits check error with dataframes without 0-index.
=> Fix a bug in DataFrameIterator ext_exist check

keras_preprocessing/image.py, tests/image_test.py
- "DataFrameIterator is regardless of x_col" issue (#60) still apears when the input dataframe has only one column(filename column).
This PR fixes this issue and adds a test.
- This PR also fixes a bug in test_dataframe_iterator_class_mode_input.
(The current API passes this test because of the previous bug.)
#60, #61
=> Fix "DataFrameIterator is regardless of x_col" bug

keras_preprocessing/image.py
This PR fixes the indentations of `flow_from_dataframe` method's docstring by removing redundant ones (which cause the argument section be **incorrectly formatted as code block** in [online documentation](https://keras.io/preprocessing/image/#flow_from_dataframe)) and adding necessary ones to make it consistent with other methods' docstring and more readable.
Nothing.
=> Fix formatting of flow_from_dataframe docstring

keras_preprocessing/image.py, tests/image_test.py
ImageDataGenerator can take a keyword argument `interpolation_order` that trickles down to `scipy.ndimage.interpolation.affine_transform` that resides in `apply_affine_transform`. At the moment the order of the spline interpolation is hard coded and set to 1 [line 323](https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image.py) This causes images of class labels to transform incorrectly. The suggested fix allows to use neaset neighbours interpolation and preserve the pixel value as integers (otherwise it turns to rational numbers that have no meaning as class labels).
for example:
```python
[[2 2 0 2 2]
[1 3 2 3 1]
[2 1 0 1 2]
[3 1 0 2 0]
[3 1 3 2 1]]
```
is transformed to 
```python
[[2.289865   1.7110896  1.8507836  2.172145   0.15832195]
[3. …
```
=> interpolation `order` for ImageDataGenerator

keras_preprocessing/image.py
Typo in docs: "rbg" instead of "rgb"
=> Update image.py. Fix noticeable typo in docs.

keras_preprocessing/image.py, tests/image_test.py
Add "sort" and "drop_duplicates" option to DataFrameIterator to be able to generate data according to just as the input dataframe order.
#72
=> Add sort and drop_duplicates option to DataFrameIterator

keras_preprocessing/image.py, tests/image_test.py
Add support for absolute paths in DataFrameIterator.
#56, #67
=> Add support for absolute paths in DataFrameIterator

keras_preprocessing/image.py, tests/image_test.py
Fix a bug in DataFrameIterator when `directory` has subdirectories
#92
=> Fix a bug in DataFrameIterator when `directory` has subdirectories

keras_preprocessing/image.py
Fixes keras-team/keras#11623
- Changed the flow_from_dataframe docstring to correct the formatting. 
- Changed the plain text link to hyperlink.
=> Fix for formatting of flow_from_dataframe in the docs.

tests/image_test.py
This PR fixes the flaky test in `test_image_data_generator`. We just set the `seed` to make sure the shuffled data would not be in the same order.
#98 
=> Fix flaky test in test_image_data_generator

keras_preprocessing/image.py
Currently, when the `classes` argument in `flow_from_dataframe` is not set, it would automatically find the classes by using pandas Series `unique` method. However, this method would return the unique values in order of appearance. Therefore, in scenarios where we have separate dataframes for training/validation/test it might result in inconsistent class indices mapping. Here is minimal example:
```python
import pandas as pd
import numpy as np
from keras.preprocessing.image import ImageDataGenerator
df_tr = pd.DataFrame({'files': ['tr_img1.jpg', 'tr_img2.jpg'],
'labels': ['cat', 'dog']})
df_val = pd.DataFrame({'files': ['val_img1.jpg', 'val_img2.jpg'],
'labels': ['dog', 'cat']})
img_gen = ImageDataGenerator()
tr_gen = img_gen.flow_from_dataframe(df_tr, 'dir', x_col='files', …
```
=> Sort classes in DataFrameIterator

keras_preprocessing/image.py
There is a check if pandas can be imported but the pandas module is not use at all in the code. I guess the committer of the code thought that you need the pandas package in the namespace in order to performs methods of a pandas object, which is not the case, that's not how namespaces work. If the user is giving a pandas Dataframe as input argument there is no need to have pandas in the scope to call methods belonging to that Dataframe. Also, the only way the user can send a pandas dataframe is because pandas is installed as a top package or depency. This PR removes that unnecessary check which is also not good practice and not Pythonic. The same thing goes with the type checking of `has_ext` and `x_col`, if you decide to go that route then you need to type check every argument in the …
=> Remove unnecessary import and type checks

keras_preprocessing/image.py
At the moment the list for possible extensions of images `white_list_formats` is hardcoded as a variable in the middle of method from both: `DirectoryIterator` and `DataframeIterator`, this is bad practice. This PR sets a unique place to update this list in the future, it sets it as a class attribute of `Iterator` since both `DirectoryIterator` and `DataframeIterator` and possible future iterators (e.g. DictionaryIterator). This helps to keep this list updated much easier as there is a single place to update it.
- [ n] This PR changes the current API [y/n] (all API changes need …
=> Move hardcoded possible file extensions as class attribute

keras_preprocessing/image/dataframe_iterator.py, keras_preprocessing/image/directory_iterator.py
Class modes are currently hardcoded in the code logic, and present in two places. In the logic check and in the error message. This PR solves both things, it's not a good practice to hardcode in the logic and if not possible then is best to make it an attribute, then this PR also refactor the error message to use this attribute such that if it's updated the error message updates as well.
=> Mode class modes as class attribute and refactor error message

keras_preprocessing/image/dataframe_iterator.py, keras_preprocessing/image/image_data_generator.py, keras_preprocessing/image/utils.py, tests/image_test.py
At the moment there is in my view unnecessary logic in the `DataframeIterator` class to handle user provided filenames without extension. Also this unnecessary logic leads to bad code practices and bugs. Some of them are:
- unnecessary double check for valid list in directory, as it only works if directory is set (137-144 and 149) it  can be done in one pass.
- logic for has_ext only checks the first element of x_col. If first element has extension
but all the other do not then the logic fails (line 153)
- why has_ext cannot be set to False if directory is none? the user should give then the fullpaths in the dataframe (lines 145-148). This logic fails because you have basically two places defining if there is an extensions (the has_ext and the filenames in the dataframe themselves).
- …
=> Remove has ext

keras_preprocessing/image/numpy_array_iterator.py, tests/image_test.py
ImageDataGenerator breaks when used with a validation_split and no labels
```
from keras_preprocessing.image import ImageDataGenerator
import numpy as np
ImageDataGenerator(validation_split=0.2).flow(x=np.random.normal(size=(100, 30, 30, 3)), subset='validation').next()
```
Solves #129 
- [ y] This PR requires new unit tests [y/n] (make sure tests are included)
=> Numpy labels

keras_preprocessing/image/numpy_array_iterator.py
This PR removes the `next` method in `NumpyIterator` since it's already in the base class `Iterator`.
=> Remove next method from NumpyIterator

keras_preprocessing/image/dataframe_iterator.py, keras_preprocessing/image/image_data_generator.py, tests/image_test.py
Currently the `DataframeIterator` has an argument `sort`. This argument doesn't add to the internal logic that `DataframeIterator` should worry about. Even if used, `sort` is used before `shuffle` for yielding the batches so there is no use for it other than having a pretty arrangement of the `filenames` attribute. But if that's what the user wants then the user can call `sort_values` on the dataframe column before sending it as an argument. This PR removes the `sort` logic which it actually only calls `sort_values` form Pandas, this improves readability in the code, easier to maintain as the logic was in several places and also in my opinion sorting has nothing to do with the logic that  `DataframeIterator` should be handling.
- [n ] This PR requires new unit tests [y/n] (make sure tests …
=> Remove sort

keras_preprocessing/image/dataframe_iterator.py, keras_preprocessing/image/directory_iterator.py, keras_preprocessing/image/image_data_generator.py, tests/image_test.py
The documentation in `flow_from_dataframe` and `DataframeIterator` states that if `directory` is None then the filenames are taken as absolute paths. I agree with this behavior, and I think this should be the default behavior if no directory parameter is given. This PR sets the default directory parameter as None and adds the corresponding tests. With this PR is enough to have the absolute paths in a Dataframe and just send that dataframe as parameter to `flow_from_dataframe`
Closses #67 #56 #116 
- [n] This PR changes the current API [y/n] (all API changes need to be approved by …
=> Default directory

keras_preprocessing/image/dataframe_iterator.py
`_list_valid_filenames_in_directory` is unused.
=> Remove unused import

keras_preprocessing/image/dataframe_iterator.py, keras_preprocessing/image/directory_iterator.py, keras_preprocessing/image/iterator.py
Currently both `DataFrameIterator` and `DirectoryIterator` contain the `_get_batches_of_transformed_samples` and `common_init` method, but both classes methods do the same thing, and the logic is slightly different. This PR merges both method versions and adds them to a Mixin class `BatchFromFilesMixin`. It needs to be a Mixin and not in the `Iterator` class because `NumpyIterator` does not use them. This PR avoid this code duplication and in my opinion also simplifies the logic a little bit by stating that is enough to collect `filepaths` and `labels` from to make things work, which makes sense. Therefore both `filepaths` and `labels` are declared as properties and an `NotImplementedError` is raised if not overwritten by the child class.
@Dref360, After @Vijayabhaskar96 pointed out some …
=> Refactor iterator

keras_preprocessing/image/dataframe_iterator.py, keras_preprocessing/image/image_data_generator.py, keras_preprocessing/image/iterator.py, tests/image_test.py
At the moment there is no support for multi-label. This PR adds multi-label support.
Minimal example:
```
import numpy as np
import scipy.misc
import pandas as pd
import random
from keras_preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
pixel_val = 1
filenames = []
for i in range(30):
filename = '/tmp/{}.jpg'.format(i)
plt.imsave(filename, pixel_val * np.ones((3, 3, 3)))
filenames.append(filename)
classes = ['dog', 'cat', ['dog', 'cat']] * 10
df = pd.DataFrame({'filename': filenames, 'class': classes}).sample(frac=1).reset_index(drop=True)
generator = ImageDataGenerator(rescale=1/255).flow_from_dataframe(
df,
batch_size=3,
target_size=(3, 3),
shuffle = False,
classes=['non-existent', 'dog', 'cat'],
class_mode='categorical',
)
assert next(generator)[1].shape == …
```
=> Multi label

keras_preprocessing/image/image_data_generator.py
At the moment the `standardize` method of `ImageDataGenerator` change the input inplace. This is a bad practice and should be avoided, as it is an unexpected behavior that faces the user and is unexpected. Since Keras puts the user first this should be avoided on any function facing the user directly. The behavior of course reduces the memory footprint and can bring benefits, but it should only be used on internal logic not on top-level user facing functions. 
This PR changes the behavior of the function to not change the user's input. It also adds tests to check that the input is not changed.
```
from keras.preprocessing.image import ImageDataGenerator
datagen = ImageDataGenerator(rescale=2)
images = np.ones((10, 128, 128, 3))
print(images.mean()) # 1.0
images_std = …
```
=> Refactor standardize

keras_preprocessing/sequence.py
Loads data and targets using a list comprehension which is much faster than a for loop & removes the need to pre-create an empty batch.
My own testing shows speedups of 1.7x-6x across all batch sizes (I've tested 4, 16, 64 and 256), multiple input/target dimensions (I've tested 1, 32 and 256 dimensional inputs & targets) and while loading the data from both disk and memory.
None
=> Improve performance of TimeSeriesGenerator by 1.7x-3x

keras_preprocessing/image/dataframe_iterator.py
At the moment there is an unused pandas import. This is also the only import of pandas in the source code which makes the import of the package break if the user hasn't pandas installed. This PR removes the import.
#154 
=> Remove unused pandas import

keras_preprocessing/image/dataframe_iterator.py, keras_preprocessing/image/directory_iterator.py, keras_preprocessing/image/image_data_generator.py, keras_preprocessing/image/iterator.py, tests/image_test.py
Currently there is no implementation of sample weights in DataFrameIterator or flow_from_dataframe. This PR adds that functionality. 
For example with this PR is now possible to train a model using sample weights, given that a column of weights is added to the pandas dataframe.
```
generator = ImageDataGenerator().flow_from_dataframe(
df,
weight_col='weights'
)
model.fit_generator(generator, epochs=2, steps_per_epoch=10)
```
Solves #147 
- [y ] This PR requires new unit tests [y/n] (make sure tests are included)
=> Add sample weights to DataFrameIterator

keras_preprocessing/image/utils.py, tests/image_test.py
Currently list_pictures  only finds images with letters expanding this to include numbers and -.
=> Add numbers and - to image names found by list_pictures.

keras_preprocessing/image/dataframe_iterator.py, keras_preprocessing/image/image_data_generator.py, keras_preprocessing/image/iterator.py, keras_preprocessing/image/utils.py, tests/image_test.py
This PR allows the user to skip the validation of images filepaths in the pandas DataFrame to speed up the instantiation process. Slow instantiation times have been reported (#171) for a big amount of filenames.  
In addition this PR adds a warning to the user if validation is on and non-valid image filenames are found.
By default image filenames are validated.
#171 
- [ y] This PR requires new unit tests [y/n] (make sure tests are included)
=> Add validate filenames parameter to DataFrameIterator

keras_preprocessing/image/image_data_generator.py
Warning about deprecation of the `sort` parameter is missing the deprecation warning type.
=> Add DeprecationWarning type to warning message

keras_preprocessing/image/dataframe_iterator.py, keras_preprocessing/image/image_data_generator.py, keras_preprocessing/image/iterator.py, tests/image_test.py
At the moment `flow_from_dataframe` does not support multi-output, i think is the excellent candidate to do that. Basically if the user sets the mode as `multi_output` then he needs to pass a list of columns and each column will represent each output. This PR enables that functionality. It is now possible to seemingly train multi output. 
In the self-contained example below I show how you could train:
- Two outputs which are single number
- Two outputs, one a single number and another a 1D array
- Two outputs, one a single number and another a 2D array
This functionality will enable several use cases (related to multi-task learning) which currently are not possible or they need to be done in a hacky way.
```
import os
import random
import numpy as np
import pandas as pd
from keras.models …
```
=> Add multi-output support to `flow_from_dataframe`

keras_preprocessing/image/dataframe_iterator.py, keras_preprocessing/image/image_data_generator.py, tests/image_test.py
Currently the `drop_diuplicates` parameter from `flow_from_dataframe`and ``DataFrameIterator` can deduplicate filenames from the user's input. My arguments for removing it are:
1.- In the same way that `sort` and `has_ext` have nothing to do with the logic the user expects and that should be handled by the `DataFrameIterator`, `drop_duplicates` also has nothing to do with the logic the class should handle. Look #123 and #122 for more explanation.
2.- It produces an unexpected behavior to the user, and several issues have been raised already because of this: #96 #175 and #181
#96 #175  #181
- [ y] This PR is backwards …
=> Remove the parameter drop_duplicates

keras_preprocessing/image/dataframe_iterator.py, keras_preprocessing/image/image_data_generator.py
Documentation about `flow_from_dataframe` does not render correctly. https://keras.io/preprocessing/image/
This PR solves the bug in the markdown.
=> Flow df docs

setup.py
Remove pinning tensorflow to a version. According to the [](https://www.tensorflow.org/install) the CPU stable version does not need any version pinning. 
As a side effect is making the CI fail.
- [n ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y ] This PR is backwards compatible [y/n]
=> Remove version pinning of tensorflow in setup.py

keras_preprocessing/image/utils.py, tests/image/directory_iterator_test.py, tests/image/utils_test.py
This PR adds the functionality to read 32-bit images (32-bit signed  integer pixel values) without losing information. This is specifically important for medical images as a great deal of information is being lost on the conversion to 8-bit.
The `load_img` function only affects and leaves 32-bit signed integer format ("I" for [PIL modes](https://pillow.readthedocs.io/en/5.1.x/handbook/concepts.html#modes)) untouched.
The `array_to_img` function now returns a 32-bit signed integer ("I" mode in PIL) if the array has a single channel and the maximum value of any pixel exceeds 255.
One thing to note is that if `array_to_img` is executed with the argument `scale=True` then even if the array is in 32-bit format, the array will be normalized to 8-bit and return an 8-bit PIL image (mode "L"). …
=> Add functionality  to read 32-bit images

keras_preprocessing/image/image_data_generator.py, tests/image/image_data_generator_test.py
Featurewise centering, normalization and ZCA whitening work incorrectly with the `rescale` parameter. This PR fixes the bug.
#100 
=> Rescale with featurewise normalization bug fix

.travis.yml, keras_preprocessing/text.py
Currently PEP8 only runs with Python 2.7, even though small differences, they can still appear between running PEP8 with Python 2.7 and Python 3.6. For example `unicode` is an unknown word in Python 3.
The testing stage by itself would break as there is a PEP8 violation. This PR also introduces the fix. Basically there is a call to `unicode` if Python2 which if flagged as unknown in Python3 (you can check the build of the first commit).
=> Add Travis stage to run PEP8 in Pythonn 3.6

keras_preprocessing/image/utils.py, keras_preprocessing/text.py, tests/image/utils_test.py
The current `load_img` function opens files but never closes them, which can cause `OSError: [Errno 24] Too many open files` if one reads in too many images in a process.
https://github.com/keras-team/keras-preprocessing/issues/260
=> autoclose files opened in load_img

.travis.yml, keras_preprocessing/sequence.py
The default parameter for padding is pre. The docs reflect the change
- [y ] This PR is backwards compatible [y/n]
- [n ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)
=> Fix sequence padding documentation

keras_preprocessing/image/image_data_generator.py, keras_preprocessing/sequence.py, keras_preprocessing/text.py
1.  Robust dtype check
`np.isscalar()` returns `True` for all scalars, not just floats or list/tuple of floats. Instead, use `isinstance()` to check dtype of `zoom_range`.
2. Dictionary code optimization
Use `{}` for dictionaries instead of `dict()` for readability and better performance.
N/A
=> Minor optimization and dtype check

keras_preprocessing/image/image_data_generator.py, keras_preprocessing/image/numpy_array_iterator.py, tests/image/dataframe_iterator_test.py, tests/image/image_data_generator_test.py, tests/sequence_test.py
Add option to handle non categorical labels when using NumpyArrayIterator/ImageDataGenerator.flow and a validation split. This is useful in non classification problems like pose estimation where the target Y is in a continuous space.
#214 
=> add ignore_class_split option for non categorical labels in image data generator

keras_preprocessing/image/affine_transformations.py, tests/image/affine_transformations_test.py
This add an option to not scale the image (to 0 - 255) when doing `random_brightness`. This also might fixes #114.
Code example :
```
brightness_range = [0.5, 2]
image = random_brightness(image, brightness_range, True) #for enable scale
image = random_brightness(image, brightness_range, False) #for disable scale
#or alternatively
image = random_brightness(image, brightness_range, scale=True)
image = random_brightness(image, brightness_range, scale=False)
#or call the apply_brightness_shift directly
image = apply_brightness_shift(image, 0.5, scale=True)
```
There's no documentation about this on keras.io...
=> Add scale param to brightness and fix some docs

keras_preprocessing/text.py
This PR moves the `document_count` constructor argument of the `Tokenizer` class to `**kwargs`.
[Quoting](https://github.com/keras-team/keras-preprocessing/pull/106#issuecomment-474632271) @fchollet:
> I don't think the `document_count` argument serves a purpose as a user-settable constructor argument. There is no use case for changing the value by hand.
> 
> However, because we use it in TF-IDF computation (and only there) it is part of the state of the `Tokenizer` and it should be saved/loaded during serialization. Removing the argument entirely isn't correct for use cases when ones tries to use TF-IDF after loading a saved `Tokenizer`.
> 
> So I think we should move this arg to `**kwargs` like we do for some private layer arguments. That way, it isn't exposed to users, it isn't …
=> Tokenizer constructor: Move document_count to **kwargs

keras_preprocessing/image/affine_transformations.py, tests/image/affine_transformations_test.py, tests/image/image_data_generator_test.py
Matrix center was set incorrectly (one off). To correct either call transform_matrix_offset_center() with h-1 ,w-1. Or  fix the sign inside that function and continue using h and w (more intuitive).
=> Set matrix center correctly

.travis.yml
Abandon Python2 tests in CI
- [n] This PR is backwards compatible [y/n]
=> Remove Python2 from CI

keras_preprocessing/__init__.py, keras_preprocessing/image/__init__.py, keras_preprocessing/image/affine_transformations.py, keras_preprocessing/image/dataframe_iterator.py, keras_preprocessing/image/directory_iterator.py, keras_preprocessing/image/image_data_generator.py, keras_preprocessing/image/iterator.py, keras_preprocessing/image/numpy_array_iterator.py, keras_preprocessing/image/utils.py, keras_preprocessing/sequence.py, keras_preprocessing/text.py, setup.py, tests/image/dataframe_iterator_test.py, tests/image/directory_iterator_test.py, tests/image/image_data_generator_test.py, tests/image/numpy_array_iterator_test.py, tests/image/utils_test.py, tests/sequence_test.py, tests/test_documentation.py, tests/text_test.py
Removed Python2 code because `keras_preprocessing` is incompatible with Python2 anymore.
=> Get rid of Python2

keras_preprocessing/image/affine_transformations.py, keras_preprocessing/image/image_data_generator.py, tests/image/affine_transformations_test.py
Prevents the apply_brightness_shift() function call to alter the image by min-max scaling it because of the missing scale parameter. Issue link: https://github.com/keras-team/keras-preprocessing/issues/327
I was using ImageDataGenerator with the parameter 'brightness_range'. This lead to unexpected behaviour where using the brightness range in interval [1,1] altered the image even though nothing should have happened. Looking more into the code, I noticed that the brightness range function generates a value 'brightness' from the uniform distribution with interval specified in the 'brightness_range' parameter, hence, the only value from U(1,1) must be 1. However, when the generated value 'brightness' is passed into the function apply_brightness_shift at line 888 seen below …
=> Added missing parameter to image_data_generator.py

keras_preprocessing/image/image_data_generator.py
This first step of removing scipy dependency (#322).
It removes scipy from image_data_generator. Next steps will remove it from additional places.
=> Removed scipy dependency from image_data_generator.

keras_preprocessing/image/dataframe_iterator.py, keras_preprocessing/image/directory_iterator.py, keras_preprocessing/image/image_data_generator.py, keras_preprocessing/image/iterator.py, keras_preprocessing/image/utils.py, tests/image/utils_test.py
Often while using `ImageDataGenerator` from local images, you want to maintain the aspect ratio of the objects itself in order to avoid models to learn the retransformation. This flag allows to maintain original aspect ratio of the objects.
An additional parameter in `flow_from_directory` is introduced, i.e. `train_datagen.flow_from_directory(keep_aspect_ratio=True)`.
In `tensorflow` there is https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/smart_resize?hl=en , copied the logic from there, since reuse was not possible due circular import ...
https://github.com/keras-team/keras/pull/4987/files
https://stackoverflow.com/questions/42467734/keras-how-to-use-imagedatagenerator-without-deforming-aspect-ratio
- [y] This PR requires new unit tests [y/n] (make sure tests are …
=> Keep original aspect ratio of objects in flow_from_directory

keras_preprocessing/image/utils.py, tests/image/utils_test.py
```
from keras_preprocessing import image 
image.load_img(**path**, target_size)
```
path can be io.Byteio before, but due to the fix in #261. It doesn't work anymore. 
I also read issues #293 and #294 for compatibility. Please let me know if there is any concerns.
#261
#293
#294
=> To support io.Bytesio
