keras-team/keras-preprocessing

.travis.yml
Add 2 news jobs where we pull keras master branch instead of the pip package.
=> Add job with kerashead

keras_preprocessing/text.py
Replacing the following construction
```python
if variable not in some_dict:
some_dict[variable] = 1
else:
some_dict[variable] += 1
```
by `defaultdict` instead: `some_dict[value] += 1`, as discussed in #1.
=> Replacing dict by defaultdict

keras_preprocessing/image.py
Add missing docs for brightness_range
[#10336 from keras](https://github.com/keras-team/keras/issues/10366)
=> Add missing docs for brightness_range

keras_preprocessing/image.py
`save_format` is a parameter to function. Fix indent to render properly.
=> Update docstring, not rendered properly.

keras_preprocessing/image.py
Should have been fixed in earlier PR itself, but anyway, this PR adds an example and fixes some typos that were made earlier.
=> adds example docstring,and fix typos for flow_from_dataframe

keras_preprocessing/image.py
This PR fixes the bug c and also returns filenames with the extensions for all the class_mode for flow_from_dataframe.
https://github.com/keras-team/keras-preprocessing/issues/60
=> fix flow_from_dataframe  no. of files found mismatch bug

MANIFEST.in, keras_preprocessing/image.py, tests/image_test.py
=> Add MANIFEST and inti

keras_preprocessing/text.py
- [n ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)
=> Fix arguments in docstrings

keras_preprocessing/image.py
=> Fixed minor typo

keras_preprocessing/image.py
Several parts in the `image.py` were checking if a file had an extensions by looping on the extensions and checking if the filename ended up with the extension. This will make one call for each possible extension in the loop. This PR instead extracts the extension from the filename and checks if membership on the set of possible extensions (that membership check is very fast).
- [n ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
=> Replace loop for checking a file extension with a single logical call

keras_preprocessing/image.py
The `next` method was implemented in each of the child classes of `Iterator` even though it was exactly the same code. This PR deduplicates the code by moving the method to the `Iterator` parent class, where it also makes sense to have it in my view (`next` method in the `Iterator` class).
=> Move next method to parent Iterator class

.github/ISSUE_TEMPLATE/a--image.md, .github/ISSUE_TEMPLATE/b--text.md
This issue template allows the automatic labeling of issues (images vs text).
None
=> Automatic labeling of issues

keras_preprocessing/image/dataframe_iterator.py, keras_preprocessing/image/directory_iterator.py, keras_preprocessing/image/image_data_generator.py
This PR improves documentations on data iteration orders. Related to [this](https://github.com/keras-team/keras/pull/12035). 
=> Improve doc

keras_preprocessing/sequence.py
Use `try...except` instead of checking for `__len__` for every item. (LBYL to EAFP)
- [N] This PR requires new unit tests [y/n] (make sure tests are included)
- [N] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [Y] This PR is backwards compatible [y/n]
- [N] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)
=> Minor optimization

keras_preprocessing/image/affine_transformations.py, keras_preprocessing/image/dataframe_iterator.py, keras_preprocessing/image/directory_iterator.py, keras_preprocessing/image/image_data_generator.py, keras_preprocessing/image/utils.py, tests/test_documentation.py
Added tests for documentation.
=> Tests for documentation

keras_preprocessing/image/image_data_generator.py
Fix a typo in the usage recommendation of the function standardize of ImageDataGenerator.
None
- [N] This PR requires new unit tests [y/n] (make sure tests are included)
- [Y] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [Y] This PR is backwards compatible [y/n]
- [N] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)
=> Fix typo in standardize usage recommendation.

keras_preprocessing/image/image_data_generator.py
Added missing grave accents(`) in line 52 and 62.
=> Fix missing snippets

keras_preprocessing/image/utils.py
This PR corrects the scaling logic.
Closes #245 
=> Update rescaling logic

keras_preprocessing/image/image_data_generator.py
=> Follow the convention

keras_preprocessing/image/dataframe_iterator.py, tests/image/dataframe_iterator_test.py
Set function sort 'classes'
To solve it, use OrderedDict
https://github.com/keras-team/keras/issues/13637
=> To solve issue #13637 in keras repo

keras_preprocessing/image/affine_transformations.py
Please note that adding unit tests is irrational before fixing this [issue](https://github.com/keras-team/keras-preprocessing/issues/315). Hence, I will add one simple test.
Fixes #316
=> Pass axes information to apply_affine_transform().

keras_preprocessing/image/affine_transformations.py, tests/image/affine_transformations_test.py
- [n] This PR is backwards compatible [y/n]
Fixes #315 
Tests were update to circumvent #316
=> Fixed the confusion between the X and Y axes.

keras_preprocessing/image/affine_transformations.py, tests/image/affine_transformations_test.py
=> Fixes #323.
